export const CHANGE_TO_PREVIOUS_MONTH = 'CHANGE_TO_PREVIOUS_MONTH';
export const CHANGE_TO_NEXT_MONTH = 'CHANGE_TO_NEXT_MONTH';
export const ADD_EVENT = 'ADD_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';
